"""empty message

Revision ID: 0825d82fccac
Revises: 0349860b3c3f
Create Date: 2019-06-16 16:24:36.713966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0825d82fccac'
down_revision = '0349860b3c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'country', 'post', ['user_id'], ['id'])
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'country', type_='foreignkey')
    # ### end Alembic commands ###
