"""empty message

Revision ID: 12b3e3d7883c
Revises: 95dc79ef398a
Create Date: 2019-06-16 17:27:45.984867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b3e3d7883c'
down_revision = '95dc79ef398a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('sentence', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###

