"""empty message

Revision ID: 22d70c859f92
Revises: 0825d82fccac
Create Date: 2019-06-16 16:26:59.391682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d70c859f92'
down_revision = '0825d82fccac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'country', 'post', ['user_id'], ['id'])
    op.add_column('post', sa.Column('sentence', sa.String(length=512), nullable=True))
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('post', 'sentence')
    op.drop_constraint(None, 'country', type_='foreignkey')
    # ### end Alembic commands ###
