"""Post table

Revision ID: 2b2f3725e0de
Revises: fc53f059b6d7
Create Date: 2019-05-26 16:25:02.516721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2f3725e0de'
down_revision = 'fc53f059b6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
