"""empty message

Revision ID: 32def69fd961
Revises: bff53dee8050
Create Date: 2019-06-16 16:46:36.141310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32def69fd961'
down_revision = 'bff53dee8050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'country', 'post', ['user_id'], ['id'])
    op.add_column('post', sa.Column('approved', sa.Boolean(), nullable=True))
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'country', type_='foreignkey')
    # ### end Alembic commands ###
