"""post table

Revision ID: 5e98e6c21f31
Revises: afeba3c142ea
Create Date: 2019-06-16 16:17:38.483020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e98e6c21f31'
down_revision = 'afeba3c142ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'country', 'post', ['user_id'], ['id'])
    op.add_column('post', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('sentence', sa.String(length=256), nullable=True))
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('post', 'sentence')
    op.drop_column('post', 'approved')
    op.drop_constraint(None, 'country', type_='foreignkey')
    # ### end Alembic commands ###
