"""empty message

Revision ID: 8539b4dd9966
Revises: 2b2f3725e0de
Create Date: 2019-05-26 17:38:06.858211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8539b4dd9966'
down_revision = '2b2f3725e0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('abrev', sa.String(length=4), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_table('country')
    # ### end Alembic commands ###
