"""empty message

Revision ID: 93e635b5ff4b
Revises: 8539b4dd9966
Create Date: 2019-05-26 22:54:05.446102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e635b5ff4b'
down_revision = '8539b4dd9966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'country', 'post', ['user_id'], ['id'])
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'country', type_='foreignkey')
    # ### end Alembic commands ###
