"""empty message

Revision ID: 95dc79ef398a
Revises: f87580e9148e
Create Date: 2019-06-16 17:14:21.902715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dc79ef398a'
down_revision = 'f87580e9148e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
