"""Post table

Revision ID: a3857b2fe88d
Revises: 
Create Date: 2019-05-26 13:52:45.877587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3857b2fe88d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_word', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_word', 'post', ['word'], unique=1)
    # ### end Alembic commands ###
