"""empty message

Revision ID: ec06e9c65b0f
Revises: 32def69fd961
Create Date: 2019-06-16 16:51:57.337116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec06e9c65b0f'
down_revision = '32def69fd961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'country', 'post', ['user_id'], ['id'])
    op.add_column('post', sa.Column('approved', sa.Boolean(), nullable=True))
    op.drop_column('post', 'countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('countries', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'country', type_='foreignkey')
    # ### end Alembic commands ###
