"""Country table

Revision ID: fc53f059b6d7
Revises: a3857b2fe88d
Create Date: 2019-05-26 15:19:18.666416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc53f059b6d7'
down_revision = 'a3857b2fe88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('country_abrev', sa.String(length=4), nullable=True))
    op.add_column('country', sa.Column('country_name', sa.String(length=32), nullable=True))
    op.drop_column('country', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('country', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('country', 'country_name')
    op.drop_column('country', 'country_abrev')
    # ### end Alembic commands ###
